@echo off
echo 🔧 Activating virtual environment...
call venv\Scripts\activate

echo 🛠️ Making initial migrations for tasks...
python manage.py makemigrations tasks --settings=core.settings.dev

echo 🚀 Applying all migrations...
python manage.py migrate --settings=core.settings.dev

echo 🏃 Running the dev server...
python manage.py runserver --settings=core.settings.dev
